// tools/collect_gu.js가 만든 파일입니다. 직접 고치지 마세요.
window.BUSAN_GU_BIDS = {
 "source": "부산 구·군 홈페이지 입찰·고시공고",
 "url": "https://www.busan.go.kr/nbgosi",
 "license": "공개 게시판의 제목·부서명·공고일만 담음(본문·첨부 제외). 일정·금액은 원문에서 확인",
 "period": {
  "from": "2026-09-04",
  "to": "2026-09-18"
 },
 "updateNote": "수집할 때마다 갱신",
 "fetched": "2026-09-19",
 "byGu": {
  "중구": 3,
  "서구": 2,
  "동구": 2,
  "영도구": 3,
  "부산진구": 1,
  "동래구": 4,
  "북구": 1,
  "해운대구": 4,
  "금정구": 1,
  "연제구": 2,
  "수영구": 3,
  "사상구": 8,
  "기장군": 0,
  "강서구": 3
 },
 "failed": {},
 "skipped": {
  "남구": "robots.txt가 수집을 막음(Disallow: /)",
  "사하구": "홈페이지 접속 403이라 확인 전 제외"
 },
 "rows": [
  {
   "no": "30104",
   "org": "부산광역시 중구 교통행정과",
   "cat": 1,
   "type": "중구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "중부소방서 뒤 노상 공영주차장 수탁자 선정 전자입찰 재공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsjunggu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=30104&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "30091",
   "org": "부산광역시 중구 재무과",
   "cat": 1,
   "type": "중구 입찰공고",
   "status": "",
   "posted": "2026-09-15",
   "title": "용역 수의계약 견적제출 공고[국제시장1길 일원 보도정비공사 폐기물 처리용...",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsjunggu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=30091&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "30084",
   "org": "부산광역시 중구 재무과",
   "cat": 1,
   "type": "중구 입찰공고",
   "status": "",
   "posted": "2026-09-11",
   "title": "공사 전자입찰 안내 공고(국제시장1길 일원 보도정비공사)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsjunggu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=30084&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 서구 공고 제2026-1026호",
   "org": "부산광역시 서구 재무과",
   "cat": 1,
   "type": "서구 고시·공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "(재공고) 남부민지구 빈집정비형 노후 주거지정비 지원사업 도시재생 활성화...",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsseogu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=36838&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 서구 공고 제2026-990호",
   "org": "부산광역시 서구 재무과",
   "cat": 1,
   "type": "서구 고시·공고",
   "status": "",
   "posted": "2026-09-14",
   "title": "공사 전자입찰 공고 [꽃마을로163번길 6 외 74개소 노후하수관로 정비...",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsseogu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=36793&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 동구 공고 제2026-793호",
   "org": "부산광역시 동구 재무과",
   "cat": 1,
   "type": "동구 입찰공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "부산진시장 엘리베이터 교체 및 보수공사",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsdonggu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=33710&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 동구 공고 제2026-786호",
   "org": "부산광역시 동구 재무과",
   "cat": 1,
   "type": "동구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "범일1동 1352-141 일원 위험축대 정비공사",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsdonggu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=33691&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 영도구 공고 제2026-977호",
   "org": "부산광역시 영도구 해양수산과",
   "cat": 1,
   "type": "영도구 고시·공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "2026년 연안어선 감척사업 대상어선 기관 및 장비 등 일괄매각 전자입찰...",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.yeongdo.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=36448&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 영도구 공고 제2026-975호",
   "org": "부산광역시 영도구 재무과",
   "cat": 1,
   "type": "영도구 고시·공고",
   "status": "",
   "posted": "2026-09-15",
   "title": "공사 전자입찰 공고[봉산마을 연결 보행환경 조성 공사(토목)]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.yeongdo.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=36445&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 영도구 공고 제2026-969호",
   "org": "부산광역시 영도구 재무과",
   "cat": 1,
   "type": "영도구 고시·공고",
   "status": "",
   "posted": "2026-09-14",
   "title": "용역 전자입찰 공고(2026년 제3종시설물 실태조사 용역)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.yeongdo.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=36434&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 부산진구 공고 제2026-1281호",
   "org": "부산광역시 부산진구 미래창조과",
   "cat": 1,
   "type": "부산진구 고시·공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "개금다락방 위탁운영 모집 긴급 (재공고)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.busanjin.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=53142&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "동래구 공고 제2026-1123호",
   "org": "부산광역시 동래구 재무과",
   "cat": 1,
   "type": "동래구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "우회전 보행자 교통사고 다발지 인프라 개선사업 수의계약 안내공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.dongnae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=45311&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "동래구 공고 제2026-1116호",
   "org": "부산광역시 동래구 재무과",
   "cat": 1,
   "type": "동래구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "법원어귀교차로 교통체계 개선사업 지장수목 이식공사 수의계약 안내공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.dongnae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=45304&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "동래구 공고 제2026-1073호",
   "org": "부산광역시 동래구 세무2과",
   "cat": 1,
   "type": "동래구 입찰공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "압류차량 인터넷 공매 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.dongnae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=45242&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "동래구 공고 제2026-1072호",
   "org": "부산광역시 동래구 세무2과",
   "cat": 1,
   "type": "동래구 입찰공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "압류차량 인터넷 공매 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.dongnae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=45241&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 북구 공고 제2026-1028호",
   "org": "부산광역시 북구 재무과",
   "cat": 1,
   "type": "북구 입찰공고",
   "status": "",
   "posted": "2026-09-15",
   "title": "[긴급]물품 경쟁입찰 공고(숙등 공유어울림파크 신축공사 냉난방 설비 구매...",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsbukgu.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=39185&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "53870",
   "org": "부산광역시 해운대구 교통행정과",
   "cat": 1,
   "type": "해운대구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "방치자전거 보관 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.haeundae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=53870&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "53863",
   "org": "부산광역시 해운대구 재무과",
   "cat": 1,
   "type": "해운대구 입찰공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "공사 입찰 공고 [ 반여동 일원 수영강 보행로 및 자전거도로 분리공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.haeundae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=53863&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "53859",
   "org": "부산광역시 해운대구 재무과",
   "cat": 1,
   "type": "해운대구 입찰공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "소액(수의) 견적제출 공고[청사포항 공중화장실 조성사업(건축)]-재공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.haeundae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=53859&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "53812",
   "org": "부산광역시 해운대구 재무과",
   "cat": 1,
   "type": "해운대구 입찰공고",
   "status": "",
   "posted": "2026-09-10",
   "title": "건설기술엔지니어링 집행계획 및 사업수행능력평가서 제출안내 및 입찰공고 [재송2동 복합청사 건립공사 감독권한대행 등 건설사업관리용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.haeundae.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=53812&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "44293",
   "org": "부산광역시 금정구 교통행정과",
   "cat": 1,
   "type": "금정구 입찰공고",
   "status": "",
   "posted": "2026-09-14",
   "title": "부곡2동공영주차장 위탁 관리 입찰 공고(2차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.geumjeong.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=44293&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 연제구 공고 제2026-1140호",
   "org": "부산광역시 연제구 재무과",
   "cat": 1,
   "type": "연제구 입찰공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "입찰공고-연제구 청소년 문화의 집 건립 기계설비공사",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.yeonje.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=43529&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 연제구 공고 제2026-1139호",
   "org": "부산광역시 연제구 재무과",
   "cat": 1,
   "type": "연제구 입찰공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "입찰공고-연제구 청소년 문화의 집 건립 전기공사",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.yeonje.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=43528&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "40516",
   "org": "부산광역시 수영구 재무과",
   "cat": 1,
   "type": "수영구 입찰공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "용역 전자입찰 공고(「2026 광안리 웹툰 콘서트」운영 용역)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.suyeong.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=40516&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "40488",
   "org": "부산광역시 수영구 재무과",
   "cat": 1,
   "type": "수영구 입찰공고",
   "status": "",
   "posted": "2026-09-11",
   "title": "용역 전자입찰 공고(「2026 수영 10분 문화권」운영 용역)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.suyeong.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=40488&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "40458",
   "org": "부산광역시 수영구 재무과",
   "cat": 1,
   "type": "수영구 입찰공고",
   "status": "",
   "posted": "2026-09-08",
   "title": "용역 전자입찰 공고(제3회 밀락루체페스타 「밀락윈터마켓」운영 용역)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.suyeong.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=40458&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1108호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "소액수의 용역 견적제출 안내 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41933&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1104호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "소액수의 용역 견적제출 안내 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41926&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1102호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "(긴급)공사 전자입찰 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41924&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1093호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "공유재산(舊 덕포1동사) 매각 일반입찰 공고(2회차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41915&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1106호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "소액수의 공사 견적제출 안내 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41928&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1095호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "소액수의 용역 견적제출 안내 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41917&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1088호",
   "org": "부산광역시 사상구 세무2과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "압류차량 매각(재공매) 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41909&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 사상구 공고 제2026-1091호",
   "org": "부산광역시 사상구 재무과",
   "cat": 1,
   "type": "사상구 입찰공고",
   "status": "",
   "posted": "2026-09-15",
   "title": "공사 전자입찰 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.sasang.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41913&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 강서구 공고 제2026-1205호",
   "org": "부산광역시 강서구 재무과",
   "cat": 1,
   "type": "강서구 고시·공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "공사 수의(견적제출) 입찰 재공고[가뭄 대응 농업용 관정 개발 공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsgangseo.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41222&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 강서구 공고 제2026-1198호",
   "org": "부산광역시 강서구 재무과",
   "cat": 1,
   "type": "강서구 고시·공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "용역 수의계약(2인견적) 안내 공고[2026년 하반기 수문(5개소) 정밀...",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsgangseo.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41211&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  },
  {
   "no": "부산광역시 강서구 공고 제2026-1189호",
   "org": "부산광역시 강서구 재무과",
   "cat": 1,
   "type": "강서구 고시·공고",
   "status": "",
   "posted": "2026-09-15",
   "title": "물품 입찰 재공고(2026년 자원회복 지역특화사업 개량조개 구매)(수정)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://eminwon.bsgangseo.go.kr/emwp/gov/mogaha/ntis/web/ofr/action/OfrAction.do?jndinm=OfrNotAncmtEJB&context=NTIS&method=selectOfrNotAncmt&methodnm=selectOfrNotAncmtRegst&not_ancmt_mgt_no=41201&homepage_pbs_yn=Y&subCheck=Y&ofr_pageSize=10&not_ancmt_se_code=02&list_gubun=&homepagetype=new"
  }
 ]
};
