// tools/collect_busan.js가 만든 파일입니다. 직접 고치지 마세요.
window.BUSAN_CITY_BIDS = {
 "source": "부산광역시청 고시공고(참여 성격만)",
 "url": "https://www.busan.go.kr/nbgosi",
 "license": "공개 게시판의 제목·부서명·공고일만 담음(본문·첨부 제외). 일정·금액은 원문에서 확인",
 "period": {
  "from": "2026-07-23",
  "to": "2026-09-18"
 },
 "updateNote": "수집할 때마다 갱신",
 "fetched": "2026-09-19",
 "scanned": 475,
 "dropped": 376,
 "rows": [
  {
   "no": "2026-2814",
   "org": "부산광역시 디지털경제실 첨단산업국 산업정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "함정 MRO 방산혁신클러스터 수행기관 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79673&gosiGbn=A"
  },
  {
   "no": "2026-2811",
   "org": "부산광역시 디지털경제실 중소상공인지원과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "「부산시 동백전 카드수수료 지원사업」 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79670&gosiGbn=A"
  },
  {
   "no": "2026-2808",
   "org": "부산광역시 여성가족국 아동청소년과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "부산광역시청소년활동진흥센터 관리·운영 민간위탁 수탁기관 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79667&gosiGbn=A"
  },
  {
   "no": "2026-2796",
   "org": "부산광역시 소방재난본부 방호조사과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "2026년 부산광역시 의용소방대 국외 정책연수 진행업체 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79647&gosiGbn=A"
  },
  {
   "no": "2026-2791",
   "org": "부산광역시 환경물정책실 공공하수인프라과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-18",
   "title": "녹산하수 방류펌프 토출배관 교체사업의 부단수 차단 공법 선정을 위한 기술제안서 제출안내 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79636&gosiGbn=A"
  },
  {
   "no": "2026-2779",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-17",
   "title": "공유재산(토지) 대부 입찰공고(금정구 부곡동 221-3)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79621&gosiGbn=A"
  },
  {
   "no": "2026-2782",
   "org": "부산광역시 기획조정실 재정관 공공기관담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "부산광역시 지방공기업 회계감사인 선임을 위한 제안서(유형별) 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79624&gosiGbn=A"
  },
  {
   "no": "2026-2756",
   "org": "부산광역시 디지털경제실 중소상공인지원과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "2026년 협동조합 비대면 마케팅 지원사업 참여기업 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79588&gosiGbn=A"
  },
  {
   "no": "2026-2751",
   "org": "부산광역시 체육국 전국체전기획단",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "2027년 전국(어울림)생활체육대축전 자원봉사자 운영 수탁기관 공개모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79582&gosiGbn=A"
  },
  {
   "no": "2026-2736",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "물품 입찰공고[부산진해경제자유구역 북측진입도로(장낙대교) 건설공사 관급자재 구매(고로슬래그 시멘트)]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79563&gosiGbn=A"
  },
  {
   "no": "2026-39",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "엄궁농산물도매시장 아스콘 포장공사 입찰 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79615&gosiGbn=A"
  },
  {
   "no": "2026-39",
   "org": "부산광역시 상수도사업본부 경영지원부 총무팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-16",
   "title": "부산의 수돗물 「순수365」 홍보디자인 공모전 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79608&gosiGbn=A"
  },
  {
   "no": "2026-2769",
   "org": "부산광역시 청년산학국 청년정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-15",
   "title": "2026년 하반기 취업연수생 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79603&gosiGbn=A"
  },
  {
   "no": "2026-2754",
   "org": "부산광역시 여성가족국 아동청소년과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-14",
   "title": "부산광역시 학교 밖 청소년 지원센터 운영 민간위탁 수탁자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79585&gosiGbn=A"
  },
  {
   "no": "2026-2727",
   "org": "부산광역시 디지털경제실 미래기술전략국 빅데이터과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-14",
   "title": "2026년 부산사회조사 및 해양산업조사 조사요원 모집공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79546&gosiGbn=A"
  },
  {
   "no": "2026-2740",
   "org": "부산광역시 사회복지국 복지정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-11",
   "title": "「금정희망의집 관리·운영」 민간위탁 수탁기관 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79567&gosiGbn=A"
  },
  {
   "no": "2026-2719",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-11",
   "title": "공사 입찰공고 [녹산하수 1차침전지 찌꺼기수집기 교체 부대공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79531&gosiGbn=A"
  },
  {
   "no": "2026-2708",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-11",
   "title": "공사 입찰공고 [사상 유아체험숲 조성공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79514&gosiGbn=A"
  },
  {
   "no": "2026-2693",
   "org": "부산광역시 대변인 미디어담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-10",
   "title": "2026 부산시 유튜브 공모전 \"통 커진 동백전! 나만의 동백백서\" 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79488&gosiGbn=A"
  },
  {
   "no": "2026-38",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-10",
   "title": "엄궁농산물도매시장 자동화재탐지설비 교체공사 입찰 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79527&gosiGbn=A"
  },
  {
   "no": "2026-2711",
   "org": "부산광역시 해양농수산국 수산진흥과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-09",
   "title": "2026년 수산물 물류환경 개선사업 보조사업자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79521&gosiGbn=A"
  },
  {
   "no": "2026-2700",
   "org": "부산광역시 디지털경제실 중소상공인지원과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-09",
   "title": "「2026 하반기 부산 사회적경제 공공구매 페어」 참가기업 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79501&gosiGbn=A"
  },
  {
   "no": "2026-2697",
   "org": "부산광역시 감사위원회 청렴담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-09",
   "title": "2026년 청렴부산 숏폼 영상 공모전 수상작 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79498&gosiGbn=A"
  },
  {
   "no": "2026-2692",
   "org": "부산광역시 주택건축국 도시정비과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-09",
   "title": "협상에 의한 계약 입찰 공고[만덕3 재개발사업 정비계획 기본방향 수립 용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79487&gosiGbn=A"
  },
  {
   "no": "2026-2656",
   "org": "부산광역시 도시계획국 도시계획과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-09",
   "title": "제11기 부산시민 도시계획 아카데미 수강생 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79424&gosiGbn=A"
  },
  {
   "no": "2026-87",
   "org": "부산광역시 시민건강국 감염병관리과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-09",
   "title": "부산광역시 한센병관리사업 위탁에 관한 조례 시행규칙 일부개정 규칙안 입법 예고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79460&gosiGbn=A"
  },
  {
   "no": "2026-2672",
   "org": "부산광역시 문화국 문화예술과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-08",
   "title": "「부산오페라하우스 건축물 미술작품 제작 및 설치 공모」 최종 당선작 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79449&gosiGbn=A"
  },
  {
   "no": "2026-2671",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-08",
   "title": "물품 입찰공고 [2026년 소방정 부산705호 예비부품 구매]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79448&gosiGbn=A"
  },
  {
   "no": "2026-73",
   "org": "부산광역시 국제수산물유통시설관리사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-08",
   "title": "불용물품(관용차량) 매각 입찰 공고(5차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79506&gosiGbn=A"
  },
  {
   "no": "2026-38",
   "org": "부산광역시 상수도사업본부 시설부 시설2팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-08",
   "title": "지방 광역상수도(취수시설) 건설공사 감독권한대행 등 건설사업관리용역 공사 감독자 배치기준(안) 공개",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79493&gosiGbn=A"
  },
  {
   "no": "2026-2652",
   "org": "부산광역시 행정자치국 자치행정과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-07",
   "title": "사단법인 부산광역시자원봉사센터장 공개모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79418&gosiGbn=A"
  },
  {
   "no": "2026-37",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-07",
   "title": "무배추동 중도매업(상장예외품모거래) 및 공유재산 사용자 모집공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79481&gosiGbn=A"
  },
  {
   "no": "2026-2657",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "공사 입찰공고 [대연3 주택재개발구역 내 배수본관 부설공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79427&gosiGbn=A"
  },
  {
   "no": "2026-2647",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "물품 입찰공고 [2026년 상수도사업본부 직원 근무복 제작]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79413&gosiGbn=A"
  },
  {
   "no": "2026-2613",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "공사 입찰공고 [사직실내체육관 석면해체 구간 마감공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79362&gosiGbn=A"
  },
  {
   "no": "2026-2611",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "공사 입찰공고 [사직실내체육관 석면해체공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79358&gosiGbn=A"
  },
  {
   "no": "2026-2591",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "용역 입찰공고 [충장고가 접속램프 A,B교 정밀안전진단용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79333&gosiGbn=A"
  },
  {
   "no": "2026-2574",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "공사 입찰공고 [용호동 일원 하수도 정비사업 구간 내 상수관로 이설공사(2공구)]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79304&gosiGbn=A"
  },
  {
   "no": "2026-2573",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-04",
   "title": "공사 입찰공고 [용호동 일원 하수도 정비사업 구간 내 상수관로 이설공사(1공구)]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79303&gosiGbn=A"
  },
  {
   "no": "2026-2641",
   "org": "부산광역시 사회복지국 장애인복지과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-03",
   "title": "2026년 발달장애인 인식개선사업 수행기관 공모",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79404&gosiGbn=A"
  },
  {
   "no": "2026-2629",
   "org": "부산광역시 시민건강국 보건위생과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-03",
   "title": "계약형 지역필수의사제 지원사업 공공기관 위탁계약 체결 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79385&gosiGbn=A"
  },
  {
   "no": "2026-70",
   "org": "부산광역시 국제수산물유통시설관리사업소 가공단지운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-03",
   "title": "수산가공선진화단지(공장시설) 입주기업 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79408&gosiGbn=A"
  },
  {
   "no": "2026-36",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-03",
   "title": "엄궁농산물도매시장 중도매인 및 공유재산 사용자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79441&gosiGbn=A"
  },
  {
   "no": "2026-118",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-02",
   "title": "용역 견적제출 안내공고[2026년 직영포장(4차) 폐아스콘 운반 및 처리용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79405&gosiGbn=A"
  },
  {
   "no": "2026-117",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-02",
   "title": "용역 견적제출 안내공고[두명터널 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79390&gosiGbn=A"
  },
  {
   "no": "2026-115",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-02",
   "title": "용역 견적제출 안내공고[반여고가교 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79388&gosiGbn=A"
  },
  {
   "no": "2026-2621",
   "org": "부산광역시 소방재난본부 구조구급과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-01",
   "title": "2026년 부산소방재난본부 소방활동 사진 공모전 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79375&gosiGbn=A"
  },
  {
   "no": "2026-2603",
   "org": "부산광역시 체육국 체육정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-09-01",
   "title": "2026년 국제체육분야 지방보조사업 공모계획(2차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79349&gosiGbn=A"
  },
  {
   "no": "2026-113",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-31",
   "title": "용역 견적제출 안내공고[2026년 공용차량 · 건설기계 보험 가입]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79369&gosiGbn=A"
  },
  {
   "no": "2026-2576",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-28",
   "title": "용역 입찰공고 [엄궁~하단동 일원 노후관 개량공사 실시설계용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79306&gosiGbn=A"
  },
  {
   "no": "2026-2557",
   "org": "부산광역시 대변인 미디어담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-28",
   "title": "부산시 어린이신문 \"빅(Big)아이 도란도란\" 7호 표지 그림 공모",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79280&gosiGbn=A"
  },
  {
   "no": "2026-2583",
   "org": "부산광역시 청년산학국 지산학협력과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-27",
   "title": "2026년 지역특화형 비자 사업(지역특화형 우수인재) 3차 모집 공고(수정)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79318&gosiGbn=A"
  },
  {
   "no": "2026-112",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-27",
   "title": "용역견적제출 안내공고[낙동강하구둑교량 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79331&gosiGbn=A"
  },
  {
   "no": "2026-2575",
   "org": "부산광역시 체육시설관리사업소 구덕운동장",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "부산광역시 구덕운동장 씨름장 관리 및 운영 민간위탁 계약 체결 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79305&gosiGbn=A"
  },
  {
   "no": "2026-2561",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "공사 입찰공고 [부산반다비 체육센터 건립사업 정보통신공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79286&gosiGbn=A"
  },
  {
   "no": "2026-2558",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "공사 입찰공고 [부산반다비 체육센터 건립사업 전기공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79281&gosiGbn=A"
  },
  {
   "no": "2026-2505",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "물품 입찰 공고[전력반도체센터 제1팹 공조시설 개보수사업 공조기 등 제작설치]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79192&gosiGbn=A"
  },
  {
   "no": "2026-111",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "용역 견적제출 안내공고[수영강변대로 복개구조물 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79323&gosiGbn=A"
  },
  {
   "no": "2026-110",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "용역 견적제출 안내공고[좌천고가교 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79321&gosiGbn=A"
  },
  {
   "no": "2026-24",
   "org": "부산광역시 수산자원연구소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-26",
   "title": "불용물품(액체크로마토그래프, 질량분석기) 매각 입찰 공고(7차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79295&gosiGbn=A"
  },
  {
   "no": "2026-2528",
   "org": "부산광역시 보건환경연구원 감염병연구부 감염병조사팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-24",
   "title": "2027년 부산시보건환경연구원 연구과제 공모",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79243&gosiGbn=A"
  },
  {
   "no": "2026-2540",
   "org": "부산광역시 디지털경제실 일자리노동과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-21",
   "title": "노동자종합복지관 관리운영 수탁기관 공개모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79257&gosiGbn=A"
  },
  {
   "no": "2026-2522",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-21",
   "title": "용역 입찰공고 [소방헬기 부산2호기(AW139) 구조인양장치 외주정비 용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79227&gosiGbn=A"
  },
  {
   "no": "2026-109",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-21",
   "title": "용역 견적제출 안내공고[대티터널(상, 하행선) 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79261&gosiGbn=A"
  },
  {
   "no": "2026-108",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-21",
   "title": "용역 견적제출 안내공고[보수천 복개구조물 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79253&gosiGbn=A"
  },
  {
   "no": "2026-33",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-21",
   "title": "엄궁농산물도매시장 청과물직판장 공유재산 시설 사용자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79274&gosiGbn=A"
  },
  {
   "no": "2026-35",
   "org": "부산광역시 상수도사업본부 남부사업소",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-20",
   "title": "불용 관용차량 매각 입찰공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79215&gosiGbn=A"
  },
  {
   "no": "2026-2504",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-19",
   "title": "물품 입찰 공고[전력반도체센터 제1팹 공조시설 개보수사업 난연케이블 구매]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79191&gosiGbn=A"
  },
  {
   "no": "2026-2503",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-19",
   "title": "물품 입찰 재공고[소득수준 중심 인구특성 지표 고도화 데이터 구매]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79190&gosiGbn=A"
  },
  {
   "no": "2026-2466",
   "org": "부산광역시 환경물정책실 탄소중립정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-18",
   "title": "2026년 노후경유차 조기폐차 지원사업 공고(2차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79145&gosiGbn=A"
  },
  {
   "no": "2026-66",
   "org": "부산광역시 국제수산물유통시설관리사업소 가공단지운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-18",
   "title": "수산가공선진화단지(공장시설) 입주기업 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79201&gosiGbn=A"
  },
  {
   "no": "2026-2446",
   "org": "부산광역시 푸른도시국 푸른숲도시과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-17",
   "title": "제14회 부산광역시 아름다운 조경상 공모 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79119&gosiGbn=A"
  },
  {
   "no": "2026-2495",
   "org": "부산광역시 상수도사업본부 경영지원부 총무팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-13",
   "title": "2026년 상수도사업본부 업무유공 직원 해외연수 진행업체 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79179&gosiGbn=A"
  },
  {
   "no": "2026-2488",
   "org": "부산광역시 기획조정실 재정관 예산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-13",
   "title": "2026년 제8회 부산광역시 모집공채 인수제안 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79171&gosiGbn=A"
  },
  {
   "no": "2026-2475",
   "org": "부산광역시 도시계획국 도로계획과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-12",
   "title": "사업수행능력 평가대상 참여기술인 업무중복도 평가자료 공개 및 의견수렴 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79155&gosiGbn=A"
  },
  {
   "no": "2026-2429",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-12",
   "title": "용역 입찰공고 [사상산업단지 완충저류시설 설치사업 건설사업관리용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79093&gosiGbn=A"
  },
  {
   "no": "2026-31",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-11",
   "title": "엄궁농산물도매시장 청과물직판장 공유재산 시설 사용자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79143&gosiGbn=A"
  },
  {
   "no": "2026-6",
   "org": "부산광역시 여성문화회관 교육복지팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-10",
   "title": "2026년도 경력단절예방 지원사업 「기업환경개선」참여 기업체 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79068&gosiGbn=A"
  },
  {
   "no": "2026-2414",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-07",
   "title": "공사 입찰공고 [탄성소재연구소 건립 조경공사]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79065&gosiGbn=A"
  },
  {
   "no": "2026-2412",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-07",
   "title": "용역 입찰공고 [새벽로 도로확장공사(잔여공사) 폐기물처리용역(폐아스콘)]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79062&gosiGbn=A"
  },
  {
   "no": "2026-106",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-07",
   "title": "용역 견적제출 안내공고[번영교(신) 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79106&gosiGbn=A"
  },
  {
   "no": "2026-29",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-07",
   "title": "엄궁농산물도매시장 청과물직판장 공유재산 시설 사용자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79110&gosiGbn=A"
  },
  {
   "no": "2026-104",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-05",
   "title": "용역 견적제출 안내공고[덕천IC 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79067&gosiGbn=A"
  },
  {
   "no": "2026-28",
   "org": "부산광역시 반여농산물도매시장관리사업소 운영팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-05",
   "title": "반여농산물도매시장 중도매인 모집공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79075&gosiGbn=A"
  },
  {
   "no": "2026-2392",
   "org": "부산광역시 청년산학국 지산학협력과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-03",
   "title": "2026년 지역특화형 비자 사업(지역특화형 우수인재) 3차 모집 공고(수정)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79034&gosiGbn=A"
  },
  {
   "no": "2026-2373",
   "org": "부산광역시 청년산학국 청년정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-03",
   "title": "2026년 부산청년 중개보수 및 이사비 지원 대상자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79008&gosiGbn=A"
  },
  {
   "no": "2026-2368",
   "org": "부산광역시 디지털경제실 투자유치과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-03",
   "title": "「2026년 컨택센터 행복충전 워크숍」 사업자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79003&gosiGbn=A"
  },
  {
   "no": "2026-2363",
   "org": "부산광역시 청년산학국 청년정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-03",
   "title": "2026년 부산청년 기쁨두배통장 참가자 모집 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78998&gosiGbn=A"
  },
  {
   "no": "2026-2345",
   "org": "부산광역시 푸른도시국 공원도시과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-03",
   "title": "2026년 부산 가든쇼 큰손바닥정원 공모전 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78962&gosiGbn=A"
  },
  {
   "no": "2026-27",
   "org": "부산광역시 엄궁농산물도매시장관리사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-08-03",
   "title": "엄궁농산물도매시장 공유재산(5개소) 신규사용자 모집 입찰 공고(제2026-5호)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=79013&gosiGbn=A"
  },
  {
   "no": "2026-103",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-30",
   "title": "용역 견적제출 안내공고[서구 낙동남로 대티터널 일원 등 2개소 포장보수공사 폐기물처리용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78995&gosiGbn=A"
  },
  {
   "no": "2026-2339",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-29",
   "title": "용역 입찰공고 [중앙대로 확장공사 폐기물(폐콘크리트)처리 용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78953&gosiGbn=A"
  },
  {
   "no": "2026-2337",
   "org": "부산광역시 기획조정실 재정관 회계재산담당관",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-29",
   "title": "물품 입찰공고 [2026년 고향기금 사업 구급장비 2종 8점 구매]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78948&gosiGbn=A"
  },
  {
   "no": "2026-2323",
   "org": "부산광역시 도시혁신균형실 건설행정과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-29",
   "title": "2026년 건설공사 하도급대금 지급보증서 발급 비용 지원사업 시행 공고(2차)",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78931&gosiGbn=A"
  },
  {
   "no": "2026-101",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-29",
   "title": "용역 견적제출 안내공고[2026년 직영포장(3차) 폐아스콘 처리용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78986&gosiGbn=A"
  },
  {
   "no": "2026-2324",
   "org": "부산광역시 디지털경제실 첨단산업국 미래에너지산업과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-27",
   "title": "2026년 부산형 재생에너지 주택지원사업 지원 공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78932&gosiGbn=A"
  },
  {
   "no": "2026-99",
   "org": "부산광역시 건설안전시험사업소 관리팀",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-27",
   "title": "용역 견적제출 안내공고[남천복개구조물 정밀안전점검용역]",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78952&gosiGbn=A"
  },
  {
   "no": "2026-2331",
   "org": "부산광역시 환경물정책실 자원순환과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-24",
   "title": "2026년 가정용 음식물쓰레기 처리기 보조금 지원사업 시행공고",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78940&gosiGbn=A"
  },
  {
   "no": "2026-274",
   "org": "부산광역시 시민건강국 건강정책과",
   "cat": 1,
   "type": "시청 고시공고",
   "status": "",
   "posted": "2026-07-23",
   "title": "부산권역난임·임산부심리상담센터 운영 업무 위탁내용 등 고시",
   "award": "",
   "open": null,
   "openText": "",
   "price": null,
   "priceNote": "",
   "url": "https://www.busan.go.kr/nbgosi/view?sno=78929&gosiGbn=A"
  }
 ]
};
